css: /assets/themes/default/css/style.css
favicon: /assets/themes/default/img/favicon.ico
touch_icon: /assets/themes/default/img/apple-touch-icon-precomposed.png
header_image: /assets/themes/default/img/title.jpg
#header_pattern: "linear-gradient(to bottom,#563d7c 0,#6f5499 100%)"
header_text_color: "white"
header_style: fluid # fluid or fit
header_title_class: "header-title"
header_description_class: "header-description"
#footer: disable
#wallpaper_image: /assets/themes/default/img/wallpaper.jpg
#wallpaper_pattern: "linear-gradient(to bottom,#563d7c 0,#6f5499 100%)"
#content_text_color: "white"
#wallpaper_repeat: repeat
navbar_brand_icon: glyphicon-home
#navbar_brand_caption: "Site Title"
#navbar_brand_image: /assets/themes/default/img/apple-touch-icon-precomposed.png
#navbar_layout: top
navbar_style: navbar-default navbar-static-top
navbar_layout: top # top or middle or bottom or none
#navbar_style: navbar-default navbar-fixed-top navbar-inverse
navbar_search_box: true
sidearea_layout: right # right or left or both or none
table_style: table-striped
#script_top: ! '
#'
#script_bottom: ! '
#'
